server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hustoj?useSSL=false&allowPublicKeyRetrieval=true
    username: lamhoang
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

upload:
  path: /home/lamhoang/testcase/upload
judger:
  token: 50f155d68905eb9fc33a23dd821204167eba0fdaf8197abbf75f8edf60ccae98
  url: http://0.0.0.0:12358

jwt:
  expiration: 604800
  secret: my-32-character-ultra-secure-and-ultra-long-secret
  header: Authorization
  route:
    authentication:
      path: /api/v1/auth

