server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_EXPOSE_PORT:3308}/${MYSQL_DATABASE:hustoj}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh&useUnicode=true&characterEncoding=UTF-8
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:passmysql}
  flyway:
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    locations: config/db
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
      jdbc:
        time_zone: GMT+7
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      database: 0
      port: ${SPRING_REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:passredis}
      timeout: 1000
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:youremail}
    password: ${MAIL_PASSWORD:yourapppassword}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

application:
  frontend:
    default-url: ${VUE_APP_URL:http://localhost:8080}

upload:
  path: ${UPLOAD_PATH:./backend/upload}
judger:
  token: ${JUDGER_TOKEN:50f155d68905eb9fc33a23dd821204167eba0fdaf8197abbf75f8edf60ccae98}
  url: ${JUDGER_URL:http://localhost:8083}

jwt:
  expiration: 604800
  secret: ${JWT_SECRET:my-32-character-ultra-secure-and-ultra-long-secret}
  header: Authorization
  route:
    authentication:
      path: /api/v1/auth

