server:
  port: 8081
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      database: 0
      port: ${SPRING_REDIS_PORT}
      password: ${REDIS_PASSWORD}
      timeout: 1000

upload:
  path: ${UPLOAD_PATH}
judger:
  token: ${JUDGER_TOKEN}
  url: ${JUDGER_URL}

jwt:
  expiration: 604800
  secret: ${JWT_SECRET}
  header: Authorization
  route:
    authentication:
      path: /api/v1/auth

